name = "freee-line"

compatibility_date = "2024-01-19"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = "./dist"

[vars]
FREEE_API_URL = "https://api.freee.co.jp"
FREEE_PUBLIC_API_URL = "https://accounts.secure.freee.co.jp"

[env.preview.vars]
FREEE_API_URL = "https://api.freee.co.jp"
FREEE_PUBLIC_API_URL = "https://accounts.secure.freee.co.jp"
LINE_LIFF_AUTH_URL = "https://liff.line.me/2006799255-85xj9bEY"
LINE_LIFF_FRONT_URL = "https://liff.line.me/2006799255-oL4RxDPz"
LINE_LIFF_AUTH_ID = "2006799255-85xj9bEY"
LINE_LIFF_FRONT_ID = "2006799255-oL4RxDPz"

[env.production.vars]
FREEE_API_URL = "https://api.freee.co.jp"
FREEE_PUBLIC_API_URL = "https://accounts.secure.freee.co.jp"
LINE_LIFF_AUTH_URL = "https://liff.line.me/2006799255-85xj9bEY"
LINE_LIFF_FRONT_URL = "https://liff.line.me/2006799255-GJ4l3wMO"
LINE_LIFF_AUTH_ID = "2006799255-85xj9bEY"
LINE_LIFF_FRONT_ID = "2006799255-GJ4l3wMO"
