compatibility_date = "2024-01-19"
compatibility_flags = ["nodejs_compat"]

main = "src/index.ts"

[env.dev]
name = "freee-line-dev"
[env.dev.vars]
APP_URL = "http://localhost:8787"
FREEE_API_URL = "https://api.freee.co.jp"
FREEE_PUBLIC_API_URL = "https://accounts.secure.freee.co.jp"

[env.stg]
name = "freee-line-stg"
[env.stg.vars]

[env.prd]
name = "freee-line-prod"
[env.prd.vars]